"""empty message

Revision ID: b5cb2e41905a
Revises: 6ea90cfcb73c
Create Date: 2019-04-02 12:04:35.445083

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b5cb2e41905a'
down_revision = '6ea90cfcb73c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=16), nullable=False))
    op.drop_column('user', 'passward')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('passward', mysql.VARCHAR(length=16), nullable=False))
    op.drop_column('user', 'password')
    op.drop_table('question')
    # ### end Alembic commands ###
